import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Syne } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "@/utils/lenis";
import ClientLayout from "@/components/layout/ClientLayout";

// 1. إعداد الخطوط
const inter = Inter({ subsets: ["latin"] });

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      /* ضفنا syne.variable هنا */
      className={` scrollbar-none  ${geistSans.variable} ${geistMono.variable} ${syne.variable} ${inter.className} antialiased`}
    >
      <ReactLenis root>
        <body>
          <ClientLayout>{children}</ClientLayout>
        </body>
      </ReactLenis>
    </html>
  );
}
