import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Syne } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

import { ReactLenis } from "@/utils/lenis";

// 1. إعداد الخطوط
const inter = Inter({ subsets: ["latin"] });

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      /* ضفنا syne.variable هنا */
      className={`overflow-y-auto scrollbar-none  ${geistSans.variable} ${geistMono.variable} ${syne.variable} ${inter.className} h-full antialiased`}
    >
      <ReactLenis root>
        <body className="min-h-full">
          <Navbar />
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
